
package ru.penzgtu.ponamorev.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWebService", targetNamespace = "http://ws.ponamorev.penzgtu.ru/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.ponamorev.penzgtu.ru/HelloWebService/getHelloStringRequest", output = "http://ws.ponamorev.penzgtu.ru/HelloWebService/getHelloStringResponse")
    public String getHelloString(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
